// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR98Y2hWPS_CXESLFYiUPVwPy3BQSF3ac',
    appId: '1:420814368276:web:acf5a7224606ff29a3c101',
    messagingSenderId: '420814368276',
    projectId: 'sonarapp-a32a9',
    authDomain: 'sonarapp-a32a9.firebaseapp.com',
    storageBucket: 'sonarapp-a32a9.firebasestorage.app',
    measurementId: 'G-PT5PSXHBS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvs74l2j2BZJxyjZZUXnn96WOhFKplO4Y',
    appId: '1:420814368276:android:dbf4eaec8fba2606a3c101',
    messagingSenderId: '420814368276',
    projectId: 'sonarapp-a32a9',
    storageBucket: 'sonarapp-a32a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrEvVQ77p0yjr7brJL5dsLOTcWnljpXI',
    appId: '1:420814368276:ios:eebc31f3bda1f5afa3c101',
    messagingSenderId: '420814368276',
    projectId: 'sonarapp-a32a9',
    storageBucket: 'sonarapp-a32a9.firebasestorage.app',
    iosBundleId: 'com.sinmiloluwa.voiceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrEvVQ77p0yjr7brJL5dsLOTcWnljpXI',
    appId: '1:420814368276:ios:1de73d15687e1cf2a3c101',
    messagingSenderId: '420814368276',
    projectId: 'sonarapp-a32a9',
    storageBucket: 'sonarapp-a32a9.firebasestorage.app',
    iosBundleId: 'com.example.voiceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR98Y2hWPS_CXESLFYiUPVwPy3BQSF3ac',
    appId: '1:420814368276:web:3b3a27b181b0e0faa3c101',
    messagingSenderId: '420814368276',
    projectId: 'sonarapp-a32a9',
    authDomain: 'sonarapp-a32a9.firebaseapp.com',
    storageBucket: 'sonarapp-a32a9.firebasestorage.app',
    measurementId: 'G-20QFB8547T',
  );
}
